version: '3.8'

services:
  backend:
    build:
      context: .
    command: >
      bash -c "
      python manage.py migrate &&
      python manage.py test --verbosity=2"
    depends_on:
      - db
    env_file:
      - ./.env.ci

  db:
    image: postgres:17
    container_name: postgres-ci
    environment:
      POSTGRES_USER: padaria_user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: padaria_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "padaria_user"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data_ci:/var/lib/postgresql/data

volumes:
  postgres_data_ci:
