# Generated by Django 5.0.3 on 2024-03-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('email', models.EmailField(max_length=75, verbose_name='E-mail')),
                ('mensagem', models.TextField(max_length=100, verbose_name='Mensagem')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='data de envio')),
                ('lido', models.BooleanField(blank=True, default=False, verbose_name='Lido')),
            ],
            options={
                'verbose_name': 'Formulario de Contato',
                'verbose_name_plural': 'Formularios de Contatos',
            },
        ),
    ]
