# Generated by Django 5.0.4 on 2024-04-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_trasacao', models.CharField(max_length=100)),
                ('valor_da_transacao', models.CharField(max_length=100)),
                ('data_da_transacao', models.DateField(auto_now_add=True)),
                ('autor_da_transacao', models.CharField(max_length=100)),
            ],
        ),
    ]
