# Generated by Django 5.0.4 on 2024-04-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacao',
            old_name='nome_da_trasacao',
            new_name='nome_da_transacao',
        ),
        migrations.AddField(
            model_name='transacao',
            name='descricao_da_transacao',
            field=models.CharField(default='valorpadrao', max_length=1000),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='data_da_transacao',
            field=models.DateField(auto_now_add=True, verbose_name='data'),
        ),
    ]
