# Generated by Django 5.1.6 on 2025-06-05 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("produtos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Data da Venda"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("PAGO", "Pago"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        db_index=True,
                        default="PENDENTE",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Valor Total",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Ativo"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venda",
                "verbose_name_plural": "Vendas",
                "ordering": ["-data"],
            },
        ),
        migrations.CreateModel(
            name="ItemVenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(verbose_name="Quantidade")),
                (
                    "preco_unitario",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Preço Unitário"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Subtotal"
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens_venda",
                        to="produtos.produtos",
                        verbose_name="Produto",
                    ),
                ),
                (
                    "venda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="vendas.vendas",
                        verbose_name="Venda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item da Venda",
                "verbose_name_plural": "Itens da Venda",
            },
        ),
        migrations.AddIndex(
            model_name="vendas",
            index=models.Index(fields=["data"], name="idx_venda_data"),
        ),
        migrations.AddIndex(
            model_name="vendas",
            index=models.Index(fields=["status"], name="idx_venda_status"),
        ),
        migrations.AddIndex(
            model_name="vendas",
            index=models.Index(fields=["ativo"], name="idx_venda_ativo"),
        ),
        migrations.AddIndex(
            model_name="itemvenda",
            index=models.Index(fields=["venda"], name="idx_item_venda"),
        ),
        migrations.AddIndex(
            model_name="itemvenda",
            index=models.Index(fields=["produto"], name="idx_item_produto"),
        ),
    ]
