# Generated by Django 5.1.6 on 2025-06-05 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produtos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=150, verbose_name="Nome do Produto"),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descrição do Produto"
                    ),
                ),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preço do Produto"
                    ),
                ),
                (
                    "estoque",
                    models.PositiveIntegerField(verbose_name="Estoque do Produto"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Criado em"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Atualizado em"
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
                "ordering": ["-criado_em"],
                "indexes": [
                    models.Index(fields=["nome"], name="idx_produto_nome"),
                    models.Index(fields=["ativo"], name="idx_produto_ativo"),
                    models.Index(fields=["criado_em"], name="idx_produto_criado_em"),
                ],
            },
        ),
    ]
