name: Django CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build containers
        run: docker compose -f backend/docker-compose.ci.yml build

      - name: Run tests
        run: docker compose -f backend/docker-compose.ci.yml up --abort-on-container-exit --exit-code-from backend

      - name: Stop containers
        if: always()
        run: docker compose -f backend/docker-compose.ci.yml down -v
