name: Django CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Logando no DockerHub (opcional, se quiser cache público)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build containers
        run: docker compose -f backend/docker-compose.ci.yml build

      - name: Run tests
        run: docker compose -f backend/docker-compose.ci.yml up --abort-on-container-exit --exit-code-from backend

      - name: Stop containers
        if: always()
        run: docker compose -f backend/docker-compose.ci.yml down -v
